version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: Europe/Paris
    commit-message:
      prefix: "build(deps): "
    open-pull-requests-limit: 2