name: Build and Test Gradle Project

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Generate Gradle wrapper if not present
      - name: Generate Gradle Wrapper
        run: |
          if [ ! -f gradlew ]; then
            gradle wrapper
          fi

      # Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Run tests
      - name: Run tests
        run: ./gradlew test